### PR TITLE
Fix Prompt_Builder method chaining

### LINKED ISSUE #19: Issue chaining methods in the new `Prompt_Builder` class
I may be doing something wrong here but in testing some of the latest changes, I'm running into an issue if I try and chain multiple methods together using the new `Prompt_Builder` class.

If I use the new `AI_Client::prompt` method, that returns a `Prompt_Builder` class, instead of `PromptBuilder` (which is expected). If I then want to call a method on that class, like `using_system_instruction`, this works fine (also expected). But if I want to call multiple methods this way, I get an error.

I think the issue here is the `Prompt_Builder` class ends up returning a `PromptBuilder` class, so chaining multiple methods together won't work.

Some practical examples.

This works:

```php
$prompt_builder = AI_Client::prompt( $prompt );
$prompt_builder = $prompt_builder->using_system_instruction( $system_instruction );
```

This will throw an error `Call to undefined method WordPress\\AiClient\\Builders\\PromptBuilder::using_provider`

```php
$prompt_builder = AI_Client::prompt( $prompt );
$prompt_builder = $prompt_builder->using_system_instruction( $system_instruction );
$prompt_builder = $prompt_builder->using_provider( $provider );
```

Not sure this is the correct approach but for testing, I changed the `__call` method of the `Prompt_Builder` class to this and it worked:

```php
public function __call( string $name, array $arguments ) {
	$callable = $this->get_builder_callable( $name );
	$result = $callable( ...$arguments );

	if ( $result instanceof PromptBuilder ) {
		return $this;
	}

	return $result;
}
```

### PR DESCRIPTION
**Pull request by JasonTheAdams**
As well described in #19, there was an issue with chaining `Prompt_Builder` fluent methods as the underlying `PromptBuilder` instance was being returned instead of the decorator.

This resolves the issue and also adds unit tests, as this would've been caught had tests been present.

Fixes #19

### CODE REVIEW

File: includes/Builders/Prompt_Builder.php [hunk 1]
```diff
@@ -124,7 +124,14 @@ public function __construct( ProviderRegistry $registry, $prompt = null ) {
...
 		$callable = $this->get_builder_callable( $name );
-		return $callable( ...$arguments );
+		$result   = $callable( ...$arguments );
+
+		// If the result is a PromptBuilder, return the current instance to allow method chaining.
+		if ( $result instanceof PromptBuilder ) {
+			return $this;
+		}
+
+		return $result;
```
Comment (felixarntz) [inline includes/Builders/Prompt_Builder.php:134]: This same fix needs to be added to `Prompt_Builder_With_WP_Error` (inside the `try` clause), while we're at it. That would currently fail with the same problem.

**Review by felixarntz — CHANGES_REQUESTED** [review]
@JasonTheAdams Looks great! Just please add the same fix to the other prompt builder class as well.

If you can add tests for that too, great, but otherwise, I'm okay just winging it for now, to unblock the problem, and because we still have to add comprehensive coverage separately anyway.

File: includes/Builders/Prompt_Builder.php (hunk 1 above)
Comment (JasonTheAdams) [reply includes/Builders/Prompt_Builder.php:134]: Resolved in 7f4ab5d and d196f39

**Review by felixarntz — APPROVED** [review]
Thanks @JasonTheAdams!
